# Use Compose version 2 to take advantage of healthcheck condition
version: "2.1"
volumes:
  grafana-pgdata:
  prometheus-data:
services:
  ###########
  # GRAFANA #
  ###########
  postgres:
    image: postgres:14.2
    volumes:
      - grafana-pgdata:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    container_name: postgres
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD", "pg_isready"]
        interval: 30s
        timeout: 1s
        retries: 5
    env_file: .env
  grafana:
    image: grafana/grafana-oss:9.0.2-ubuntu
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
        - ./grafana.ini:/etc/grafana/grafana.ini
        - ./provisioning:/etc/grafana/provisioning
        - ./dashboards:/var/lib/grafana/dashboards
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
  git-sync:
    image: k8s.gcr.io/git-sync/git-sync:v3.5.0
    container_name: git-sync
    user: "${UID}:${GID}"
    environment:
      GIT_SYNC_REPO: "https://github.com/ducnm0711/gf-dummy-dashboards"
      GIT_SYNC_BRANCH: "main"
      GIT_SYNC_ROOT: "/tmp/git"
      GIT_SYNC_WAIT: "10"
    volumes:
      - ./dashboards:/tmp/git
    env_file: .env
  ##############
  # PROMETHEUS #
  ##############
  prometheus:
    image: quay.io/prometheus/prometheus:v2.34.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
  #################
  # ALERT MANAGER #
  #################
  # alertmanager:
  #   image: prom/alertmanager
  #   ports:
  #     - 9093:9093
  #   volumes:
  #     - ./alertmanager/:/etc/alertmanager/
  #   command:
  #     - '--config.file=/etc/alertmanager/config.yml'
  #     - '--storage.path=/alertmanager'
